[package]
name = "input-leap"
version = "2.4.0"
edition = "2021"

[lib]
name = "inputleap"
path = "rust_src/lib.rs"
crate-type = ["staticlib", "dylib"]

[dependencies]
libc = "0.2.125"

[build-dependencies]
bindgen = "0.59.2"
